### ISSUE TITLE
Make searches (optionally) more R-focussed

### ISSUE THREAD

**Issue by jonocarroll** [coatless/searcher#10]
Queries are coming from `R`; there's a high chance the user wants to search for something `R`-related (though maybe this is the new way to find cat pictures). 

Compare

```
search_google("plot points")
```

![screen shot 2018-01-31 at 11 08 41 am](https://user-images.githubusercontent.com/9496865/35599135-356c35bc-0677-11e8-9054-ba31fc8221df.jpg)

with

```
search_google("plot points rstats")
```

![screen shot 2018-01-31 at 11 08 56 am](https://user-images.githubusercontent.com/9496865/35599141-3d74a398-0677-11e8-8350-3c6ee8611e5a.jpg)

You already have `rlang = TRUE` for some engines but what about 

```
search_google(query, rstats = TRUE)
```

to append `rstats` to the query?

**Comment by coatless** [comment]
You raise a great point. I'll likely turn this option on in the next release.

However, I'm hesitant to use "rstats" in the search because google autocorrects to "stats" (as shown in screenshot). 

Playing around with a couple terms, it seems like either:

- r language
- r programming 

are better suited to improve the signal. Thoughts?
